[package]
name = "phanalist"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
colored = "2.0.0"
jwalk = "0.8.1"
lsp-server = "0.7.0"
lsp-types = "0.94.0"
# lsp-server = "0.7.0"
# lsp-types = "0.94.0"
php-parser-rs = { git = "https://github.com/php-rust-tools/parser", version = "0.1.3" }
rocksdb = "0.21.0"
serde = "1.0.152"
serde_json = "1.0.93"
serde_yaml = "0.9.21"
tokio = { version = "1.28.2", features = ["full"] }
walkdir = "2.3.2"

[build-dependencies]
bindgen = "0.65.1"
