[package]
name = "phanalist"
version = "0.1.21"
edition = "2021"
lincese = "MIT"
description = "Performant static analyzer for PHP, which is extremely easy to use. It helps you catch common mistakes in your PHP code."
readme = "./README.md"
categories = ["development-tools"]
include = [
  "/Cargo.toml",
  "/LICENSE",
  "/README.md",
  "/src/**",
]
keywords = ["PHP", "code quality", "code review"]
license = "MIT"
repository = "https://github.com/denzyldick/phanalist"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
cli-table = "0.4.7"
colored = "2.0.0"
jwalk = "0.8.1"
php-parser-rs = { git = "https://github.com/php-rust-tools/parser", version = "0.1.3" }
serde = "1.0.152"
serde_json = "1.0.93"
serde_yaml = "0.9.21"
tokio = { version = "1.28.2", features = ["full"] }
walkdir = "2.3.2"
indicatif = "0.17.7"
exitcode = "1.1.2"
memory-stats = "1.0.0"
human_bytes = "0.4"

[build-dependencies]
bindgen = "0.65.1"
