[package]
name = "phanalist"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
colored = "2.0.0"
jwalk = "0.8.1"
php-parser-rs = { git = "https://github.com/php-rust-tools/parser", version = "0.1.0" }
rocksdb = "0.20.1"
serde = "1.0.152"
serde_json = "1.0.93"
serde_yaml = "0.9.21"
walkdir = "2.3.2"

